name: Quiz Answer Checker

on:
  issue_comment:
    types: [created]

# Add permissions section to allow necessary operations
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  check-answer:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'quiz')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Check Answer
        id: check-answer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the issue details
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          COMMENT_BODY="${{ github.event.comment.body }}"
          COMMENTER="${{ github.event.comment.user.login }}"
          
          # Check if issue is already closed - if so, no more rewards
          ISSUE_STATE=$(gh issue view $ISSUE_NUMBER --json state --jq '.state')
          if [ "$ISSUE_STATE" = "CLOSED" ]; then
            gh issue comment $ISSUE_NUMBER --body "Sorry @$COMMENTER, this quiz has already been completed by another user and is now closed."
            echo "eligible=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Check for instance number in title to support multiple users
          INSTANCE_ID=$(echo "${{ github.event.issue.title }}" | grep -oE 'Instance [0-9]+' | grep -oE '[0-9]+' || echo "1")
          
          # Extract correct answer from issue body using regex
          CORRECT_ANSWER=$(echo "$ISSUE_BODY" | grep -o "<!-- CORRECT_ANSWER: [A-Z] -->" | cut -d' ' -f3)
          
          # Extract user's answer (assume they just post A, B, C, etc.)
          USER_ANSWER=$(echo "$COMMENT_BODY" | tr -d '[:space:]')
          
          echo "Checking answer: User answered $USER_ANSWER, correct is $CORRECT_ANSWER"
          
          # If answer is correct
          if [ "$USER_ANSWER" = "$CORRECT_ANSWER" ]; then
            echo "correct=true" >> $GITHUB_OUTPUT
            echo "commenter=$COMMENTER" >> $GITHUB_OUTPUT
          else
            echo "correct=false" >> $GITHUB_OUTPUT
            # Comment that the answer is incorrect
            gh issue comment $ISSUE_NUMBER --body "Sorry @$COMMENTER, that's not the correct answer. Please try again!"
          fi
      
      # Only run next steps if answer is correct
      - name: Process Correct Answer
        if: steps.check-answer.outputs.correct == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          COMMENTER="${{ steps.check-answer.outputs.commenter }}"
          
          # Comment that the answer is correct
          gh issue comment $ISSUE_NUMBER --body "Correct answer, @$COMMENTER! 🎉"
          
          # Record the correct answer in a file in the main branch
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Create directory if it doesn't exist
          mkdir -p quiz-answers
          
          # Create and commit answer file
          echo "Quiz question #$ISSUE_NUMBER answered correctly by @$COMMENTER on $(date)" >> quiz-answers/successful-answers.md
          
          # Commit and push directly to main (no PR needed)
          git add quiz-answers/successful-answers.md
          git commit -m "Record correct answer to quiz #$ISSUE_NUMBER by @$COMMENTER"
          git push origin HEAD:main
          
          # Close the issue
          gh issue close $ISSUE_NUMBER --comment "This quiz question has been completed successfully by @$COMMENTER. Reward tokens will be distributed according to the Roxonn platform rules."

      - name: Add Social Share Instructions
        if: steps.check-answer.outputs.correct == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          COMMENTER="${{ steps.check-answer.outputs.commenter }}"
          
          # Add social media sharing instructions
          gh issue comment $ISSUE_NUMBER --body "Congratulations @$COMMENTER! You've earned tokens for completing this quiz question. Share your achievement on social media with the hashtag #EarnWithRoxn!"
